// <auto-generated />
using System;
using AgeNexus.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AgeNexus.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AgeNexusDbContext))]
    [Migration("20260901133545_AddCompetitionCore")]
    partial class AddCompetitionCore
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AgeNexus.Domain.Clans.Clan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByPlayerProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_player_profile_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("tag");

                    b.HasKey("Id")
                        .HasName("pk_clans");

                    b.HasIndex("CreatedByPlayerProfileId");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ux_clans_name");

                    b.HasIndex("Tag")
                        .IsUnique()
                        .HasDatabaseName("ux_clans_tag");

                    b.ToTable("clans", "public");
                });

            modelBuilder.Entity("AgeNexus.Domain.Clans.ClanMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClanId")
                        .HasColumnType("uuid")
                        .HasColumnName("clan_id");

                    b.Property<DateTimeOffset?>("EndedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at_utc");

                    b.Property<Guid>("PlayerProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_profile_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_clan_memberships");

                    b.HasIndex("ClanId");

                    b.HasIndex("PlayerProfileId")
                        .IsUnique()
                        .HasDatabaseName("ux_clan_memberships_active_player")
                        .HasFilter("ended_at_utc IS NULL");

                    b.ToTable("clan_memberships", "public");
                });

            modelBuilder.Entity("AgeNexus.Domain.Competition.PointEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BeneficiaryId")
                        .HasColumnType("uuid")
                        .HasColumnName("beneficiary_id");

                    b.Property<string>("CalculationDetails")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("calculation_details");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("EvidenceLevel")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("evidence_level");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("kind");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("match_id");

                    b.Property<decimal>("Points")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("points");

                    b.Property<Guid?>("ReversesEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("reverses_event_id");

                    b.Property<string>("RuleVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("rule_version");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("scope");

                    b.Property<Guid?>("SeasonId")
                        .HasColumnType("uuid")
                        .HasColumnName("season_id");

                    b.Property<string>("SourceKey")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("source_key");

                    b.HasKey("Id")
                        .HasName("pk_point_events");

                    b.HasIndex("ReversesEventId")
                        .IsUnique()
                        .HasDatabaseName("ux_point_events_reversal")
                        .HasFilter("reverses_event_id IS NOT NULL");

                    b.HasIndex("BeneficiaryId", "SeasonId", "SourceKey")
                        .HasDatabaseName("ix_point_events_repetition");

                    b.HasIndex("MatchId", "BeneficiaryId", "SeasonId", "Scope", "RuleVersion", "Kind")
                        .IsUnique()
                        .HasDatabaseName("ux_point_events_idempotency");

                    b.ToTable("point_events", "public");
                });

            modelBuilder.Entity("AgeNexus.Domain.Competition.RatingEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BeneficiaryId")
                        .HasColumnType("uuid")
                        .HasColumnName("beneficiary_id");

                    b.Property<string>("CalculationDetails")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("calculation_details");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<decimal>("Delta")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("delta");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("kind");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("match_id");

                    b.Property<Guid?>("ReversesEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("reverses_event_id");

                    b.Property<string>("RuleVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("rule_version");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("scope");

                    b.Property<Guid?>("SeasonId")
                        .HasColumnType("uuid")
                        .HasColumnName("season_id");

                    b.HasKey("Id")
                        .HasName("pk_rating_events");

                    b.HasIndex("ReversesEventId")
                        .IsUnique()
                        .HasDatabaseName("ux_rating_events_reversal")
                        .HasFilter("reverses_event_id IS NOT NULL");

                    b.HasIndex("MatchId", "BeneficiaryId", "SeasonId", "Scope", "RuleVersion", "Kind")
                        .IsUnique()
                        .HasDatabaseName("ux_rating_events_idempotency");

                    b.ToTable("rating_events", "public");
                });

            modelBuilder.Entity("AgeNexus.Domain.Competition.Season", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("EndsAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at_utc");

                    b.Property<Guid>("GameEditionId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_edition_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("StartsAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_seasons");

                    b.HasIndex("GameEditionId", "StartsAtUtc")
                        .IsUnique()
                        .HasDatabaseName("ux_seasons_edition_start");

                    b.ToTable("seasons", "public", t =>
                        {
                            t.HasCheckConstraint("ck_seasons_interval", "ends_at_utc > starts_at_utc");
                        });
                });

            modelBuilder.Entity("AgeNexus.Domain.Competition.TeamLineup", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("GameEditionId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_edition_id");

                    b.Property<string>("NormalizedKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("normalized_key");

                    b.HasKey("Id")
                        .HasName("pk_team_lineups");

                    b.HasIndex("GameEditionId");

                    b.HasIndex("NormalizedKey")
                        .IsUnique()
                        .HasDatabaseName("ux_team_lineups_key");

                    b.ToTable("team_lineups", "public");
                });

            modelBuilder.Entity("AgeNexus.Domain.Competition.TeamLineupMember", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("PlayerProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_profile_id");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<Guid>("team_lineup_id")
                        .HasColumnType("uuid")
                        .HasColumnName("team_lineup_id");

                    b.HasKey("Id")
                        .HasName("pk_team_lineup_members");

                    b.HasIndex("PlayerProfileId");

                    b.HasIndex("team_lineup_id", "PlayerProfileId")
                        .IsUnique()
                        .HasDatabaseName("ux_team_lineup_members_player");

                    b.HasIndex("team_lineup_id", "Position")
                        .IsUnique()
                        .HasDatabaseName("ux_team_lineup_members_position");

                    b.ToTable("team_lineup_members", "public");
                });

            modelBuilder.Entity("AgeNexus.Domain.EvidenceAndModeration.ChallengeTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("code");

                    b.Property<string>("ConfigurationFingerprint")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("configuration_fingerprint");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<Guid>("GameEditionId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_edition_id");

                    b.Property<DateTimeOffset>("IssuedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at_utc");

                    b.Property<Guid>("PlayerProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_profile_id");

                    b.Property<DateTimeOffset?>("UsedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_challenge_tickets");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_challenge_tickets_code");

                    b.HasIndex("GameEditionId");

                    b.HasIndex("PlayerProfileId");

                    b.ToTable("challenge_tickets", "public");
                });

            modelBuilder.Entity("AgeNexus.Domain.EvidenceAndModeration.MatchEvidence", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ExternalUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("external_url");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("kind");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("match_id");

                    b.Property<string>("ObjectKey")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("object_key");

                    b.Property<string>("Sha256")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sha256");

                    b.Property<DateTimeOffset>("SubmittedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at_utc");

                    b.Property<Guid>("SubmittedByPlayerProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("submitted_by_player_profile_id");

                    b.HasKey("Id")
                        .HasName("pk_match_evidence");

                    b.HasIndex("MatchId");

                    b.HasIndex("Sha256")
                        .IsUnique()
                        .HasDatabaseName("ux_match_evidence_sha256")
                        .HasFilter("sha256 IS NOT NULL");

                    b.HasIndex("SubmittedByPlayerProfileId");

                    b.ToTable("match_evidence", "public");
                });

            modelBuilder.Entity("AgeNexus.Domain.EvidenceAndModeration.VerificationDecision", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("DecidedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at_utc");

                    b.Property<Guid?>("DecidedByApplicationUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("decided_by_application_user_id");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("match_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reason");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_verification_decisions");

                    b.HasIndex("MatchId", "DecidedAtUtc")
                        .HasDatabaseName("ix_verification_decisions_match_time");

                    b.ToTable("verification_decisions", "public");
                });

            modelBuilder.Entity("AgeNexus.Domain.GameCatalog.AiDifficulty", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("GameEditionId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_edition_id");

                    b.Property<int>("InternalLevel")
                        .HasColumnType("integer")
                        .HasColumnName("internal_level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_ai_difficulties");

                    b.HasIndex("GameEditionId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_ai_difficulties_edition_name");

                    b.ToTable("ai_difficulties", "public", t =>
                        {
                            t.HasCheckConstraint("ck_ai_difficulties_internal_level", "internal_level BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("AgeNexus.Domain.GameCatalog.Faction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("GameEditionId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_edition_id");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_factions");

                    b.HasIndex("GameEditionId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_factions_edition_slug");

                    b.ToTable("factions", "public");
                });

            modelBuilder.Entity("AgeNexus.Domain.GameCatalog.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_games");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_games_slug");

                    b.ToTable("games", "public");
                });

            modelBuilder.Entity("AgeNexus.Domain.GameCatalog.GameEdition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_game_editions");

                    b.HasIndex("GameId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_game_editions_game_slug");

                    b.ToTable("game_editions", "public");
                });

            modelBuilder.Entity("AgeNexus.Domain.GameCatalog.GamePatch", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("EffectiveFromUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_from_utc");

                    b.Property<DateTimeOffset?>("EffectiveToUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_to_utc");

                    b.Property<Guid>("GameEditionId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_edition_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_game_patches");

                    b.HasIndex("GameEditionId", "EffectiveFromUtc")
                        .IsUnique()
                        .HasDatabaseName("ux_game_patches_edition_start");

                    b.ToTable("game_patches", "public");
                });

            modelBuilder.Entity("AgeNexus.Domain.GameCatalog.MapDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("GameEditionId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_edition_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_map_definitions");

                    b.HasIndex("GameEditionId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_maps_edition_slug");

                    b.ToTable("map_definitions", "public");
                });

            modelBuilder.Entity("AgeNexus.Domain.Matches.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CreatedByPlayerProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_player_profile_id");

                    b.Property<Guid>("GameEditionId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_edition_id");

                    b.Property<Guid?>("GamePatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_patch_id");

                    b.Property<Guid?>("MapDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("map_definition_id");

                    b.Property<string>("Nature")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("nature");

                    b.Property<DateTimeOffset>("PlayedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("played_at_utc");

                    b.Property<Guid?>("SeasonId")
                        .HasColumnType("uuid")
                        .HasColumnName("season_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_matches");

                    b.HasIndex("CreatedByPlayerProfileId")
                        .HasDatabaseName("ix_matches_created_by_player_profile");

                    b.HasIndex("GamePatchId")
                        .HasDatabaseName("ix_matches_patch");

                    b.HasIndex("MapDefinitionId")
                        .HasDatabaseName("ix_matches_map");

                    b.HasIndex("PlayedAtUtc")
                        .HasDatabaseName("ix_matches_played_at_utc");

                    b.HasIndex("SeasonId")
                        .HasDatabaseName("ix_matches_season");

                    b.HasIndex("GameEditionId", "Status")
                        .HasDatabaseName("ix_matches_edition_status");

                    b.ToTable("matches", "public");
                });

            modelBuilder.Entity("AgeNexus.Domain.Matches.MatchConfirmation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("comment");

                    b.Property<DateTimeOffset>("DecidedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at_utc");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("decision");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("match_id");

                    b.Property<Guid>("PlayerProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_profile_id");

                    b.HasKey("Id")
                        .HasName("pk_match_confirmations");

                    b.HasIndex("PlayerProfileId");

                    b.HasIndex("MatchId", "PlayerProfileId")
                        .IsUnique()
                        .HasDatabaseName("ux_match_confirmations_match_player");

                    b.ToTable("match_confirmations", "public");
                });

            modelBuilder.Entity("AgeNexus.Domain.Matches.MatchParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AiDifficultyId")
                        .HasColumnType("uuid")
                        .HasColumnName("ai_difficulty_id");

                    b.Property<Guid?>("FactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("faction_id");

                    b.Property<string>("FactionSelection")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("faction_selection");

                    b.Property<Guid?>("PlayerProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_profile_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.Property<Guid>("team_id")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.HasKey("Id")
                        .HasName("pk_match_participants");

                    b.HasIndex("AiDifficultyId")
                        .HasDatabaseName("ix_match_participants_ai_difficulty");

                    b.HasIndex("FactionId")
                        .HasDatabaseName("ix_match_participants_faction");

                    b.HasIndex("PlayerProfileId")
                        .HasDatabaseName("ix_match_participants_player_profile");

                    b.HasIndex("team_id")
                        .HasDatabaseName("ix_match_participants_team");

                    b.ToTable("match_participants", "public", t =>
                        {
                            t.HasCheckConstraint("ck_match_participants_identity", "(type = 'Human' AND player_profile_id IS NOT NULL AND ai_difficulty_id IS NULL) OR (type = 'ArtificialIntelligence' AND player_profile_id IS NULL AND ai_difficulty_id IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("AgeNexus.Domain.Matches.MatchRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ChangedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at_utc");

                    b.Property<Guid>("ChangedByApplicationUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("changed_by_application_user_id");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("match_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reason");

                    b.Property<string>("Snapshot")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("snapshot");

                    b.HasKey("Id")
                        .HasName("pk_match_revisions");

                    b.HasIndex("MatchId", "ChangedAtUtc")
                        .HasDatabaseName("ix_match_revisions_match_time");

                    b.ToTable("match_revisions", "public");
                });

            modelBuilder.Entity("AgeNexus.Domain.Matches.MatchTeam", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("result");

                    b.Property<Guid>("match_id")
                        .HasColumnType("uuid")
                        .HasColumnName("match_id");

                    b.HasKey("Id")
                        .HasName("pk_match_teams");

                    b.HasIndex("match_id", "Position")
                        .IsUnique()
                        .HasDatabaseName("ux_match_teams_match_position");

                    b.ToTable("match_teams", "public");
                });

            modelBuilder.Entity("AgeNexus.Domain.Players.PlayerFavoriteFaction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("FactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("faction_id");

                    b.Property<Guid>("PlayerProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_profile_id");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.HasKey("Id")
                        .HasName("pk_player_favorite_factions");

                    b.HasIndex("FactionId");

                    b.HasIndex("PlayerProfileId", "FactionId")
                        .IsUnique()
                        .HasDatabaseName("ux_player_favorite_factions_player_faction");

                    b.HasIndex("PlayerProfileId", "Priority")
                        .IsUnique()
                        .HasDatabaseName("ux_player_favorite_factions_player_priority");

                    b.ToTable("player_favorite_factions", "public", t =>
                        {
                            t.HasCheckConstraint("ck_player_favorite_factions_priority", "priority BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("AgeNexus.Domain.Players.PlayerProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ApplicationUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_user_id");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("avatar_url");

                    b.Property<string>("Bio")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("bio");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("location");

                    b.HasKey("Id")
                        .HasName("pk_player_profiles");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique()
                        .HasDatabaseName("ux_player_profiles_application_user_id")
                        .HasFilter("application_user_id IS NOT NULL");

                    b.HasIndex("DisplayName")
                        .HasDatabaseName("ix_player_profiles_display_name");

                    b.ToTable("player_profiles", "public");
                });

            modelBuilder.Entity("AgeNexus.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("users", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("roles", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("role_claims", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("user_claims", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("user_logins", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("user_tokens", "identity");
                });

            modelBuilder.Entity("AgeNexus.Domain.Clans.Clan", b =>
                {
                    b.HasOne("AgeNexus.Domain.Players.PlayerProfile", null)
                        .WithMany()
                        .HasForeignKey("CreatedByPlayerProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_clans_founder");
                });

            modelBuilder.Entity("AgeNexus.Domain.Clans.ClanMembership", b =>
                {
                    b.HasOne("AgeNexus.Domain.Clans.Clan", null)
                        .WithMany()
                        .HasForeignKey("ClanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_clan_memberships_clan");

                    b.HasOne("AgeNexus.Domain.Players.PlayerProfile", null)
                        .WithMany()
                        .HasForeignKey("PlayerProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_clan_memberships_player");
                });

            modelBuilder.Entity("AgeNexus.Domain.Competition.Season", b =>
                {
                    b.HasOne("AgeNexus.Domain.GameCatalog.GameEdition", null)
                        .WithMany()
                        .HasForeignKey("GameEditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_seasons_game_edition");
                });

            modelBuilder.Entity("AgeNexus.Domain.Competition.TeamLineup", b =>
                {
                    b.HasOne("AgeNexus.Domain.GameCatalog.GameEdition", null)
                        .WithMany()
                        .HasForeignKey("GameEditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_team_lineups_game_edition");
                });

            modelBuilder.Entity("AgeNexus.Domain.Competition.TeamLineupMember", b =>
                {
                    b.HasOne("AgeNexus.Domain.Players.PlayerProfile", null)
                        .WithMany()
                        .HasForeignKey("PlayerProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_team_lineup_members_player");

                    b.HasOne("AgeNexus.Domain.Competition.TeamLineup", null)
                        .WithMany("Members")
                        .HasForeignKey("team_lineup_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_team_lineup_members_lineup");
                });

            modelBuilder.Entity("AgeNexus.Domain.EvidenceAndModeration.ChallengeTicket", b =>
                {
                    b.HasOne("AgeNexus.Domain.GameCatalog.GameEdition", null)
                        .WithMany()
                        .HasForeignKey("GameEditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_challenge_tickets_edition");

                    b.HasOne("AgeNexus.Domain.Players.PlayerProfile", null)
                        .WithMany()
                        .HasForeignKey("PlayerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_challenge_tickets_player");
                });

            modelBuilder.Entity("AgeNexus.Domain.EvidenceAndModeration.MatchEvidence", b =>
                {
                    b.HasOne("AgeNexus.Domain.Matches.Match", null)
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_match_evidence_match");

                    b.HasOne("AgeNexus.Domain.Players.PlayerProfile", null)
                        .WithMany()
                        .HasForeignKey("SubmittedByPlayerProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_match_evidence_submitter");
                });

            modelBuilder.Entity("AgeNexus.Domain.EvidenceAndModeration.VerificationDecision", b =>
                {
                    b.HasOne("AgeNexus.Domain.Matches.Match", null)
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_verification_decisions_match");
                });

            modelBuilder.Entity("AgeNexus.Domain.GameCatalog.AiDifficulty", b =>
                {
                    b.HasOne("AgeNexus.Domain.GameCatalog.GameEdition", null)
                        .WithMany()
                        .HasForeignKey("GameEditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ai_difficulties_game_edition");
                });

            modelBuilder.Entity("AgeNexus.Domain.GameCatalog.Faction", b =>
                {
                    b.HasOne("AgeNexus.Domain.GameCatalog.GameEdition", null)
                        .WithMany()
                        .HasForeignKey("GameEditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_factions_game_edition");
                });

            modelBuilder.Entity("AgeNexus.Domain.GameCatalog.GameEdition", b =>
                {
                    b.HasOne("AgeNexus.Domain.GameCatalog.Game", null)
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_game_editions_game");
                });

            modelBuilder.Entity("AgeNexus.Domain.GameCatalog.GamePatch", b =>
                {
                    b.HasOne("AgeNexus.Domain.GameCatalog.GameEdition", null)
                        .WithMany()
                        .HasForeignKey("GameEditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_game_patches_game_edition");
                });

            modelBuilder.Entity("AgeNexus.Domain.GameCatalog.MapDefinition", b =>
                {
                    b.HasOne("AgeNexus.Domain.GameCatalog.GameEdition", null)
                        .WithMany()
                        .HasForeignKey("GameEditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_maps_game_edition");
                });

            modelBuilder.Entity("AgeNexus.Domain.Matches.Match", b =>
                {
                    b.HasOne("AgeNexus.Domain.Players.PlayerProfile", null)
                        .WithMany()
                        .HasForeignKey("CreatedByPlayerProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_matches_created_by_player_profile");

                    b.HasOne("AgeNexus.Domain.GameCatalog.GameEdition", null)
                        .WithMany()
                        .HasForeignKey("GameEditionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_matches_game_edition");

                    b.HasOne("AgeNexus.Domain.GameCatalog.GamePatch", null)
                        .WithMany()
                        .HasForeignKey("GamePatchId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_matches_patch");

                    b.HasOne("AgeNexus.Domain.GameCatalog.MapDefinition", null)
                        .WithMany()
                        .HasForeignKey("MapDefinitionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_matches_map");

                    b.HasOne("AgeNexus.Domain.Competition.Season", null)
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_matches_season");
                });

            modelBuilder.Entity("AgeNexus.Domain.Matches.MatchConfirmation", b =>
                {
                    b.HasOne("AgeNexus.Domain.Matches.Match", null)
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_match_confirmations_match");

                    b.HasOne("AgeNexus.Domain.Players.PlayerProfile", null)
                        .WithMany()
                        .HasForeignKey("PlayerProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_match_confirmations_player");
                });

            modelBuilder.Entity("AgeNexus.Domain.Matches.MatchParticipant", b =>
                {
                    b.HasOne("AgeNexus.Domain.GameCatalog.AiDifficulty", null)
                        .WithMany()
                        .HasForeignKey("AiDifficultyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_match_participants_ai_difficulty");

                    b.HasOne("AgeNexus.Domain.GameCatalog.Faction", null)
                        .WithMany()
                        .HasForeignKey("FactionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_match_participants_faction");

                    b.HasOne("AgeNexus.Domain.Players.PlayerProfile", null)
                        .WithMany()
                        .HasForeignKey("PlayerProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_match_participants_player_profile");

                    b.HasOne("AgeNexus.Domain.Matches.MatchTeam", null)
                        .WithMany("Participants")
                        .HasForeignKey("team_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_match_participants_team");
                });

            modelBuilder.Entity("AgeNexus.Domain.Matches.MatchRevision", b =>
                {
                    b.HasOne("AgeNexus.Domain.Matches.Match", null)
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_match_revisions_match");
                });

            modelBuilder.Entity("AgeNexus.Domain.Matches.MatchTeam", b =>
                {
                    b.HasOne("AgeNexus.Domain.Matches.Match", null)
                        .WithMany("Teams")
                        .HasForeignKey("match_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_match_teams_match");
                });

            modelBuilder.Entity("AgeNexus.Domain.Players.PlayerFavoriteFaction", b =>
                {
                    b.HasOne("AgeNexus.Domain.GameCatalog.Faction", null)
                        .WithMany()
                        .HasForeignKey("FactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_player_favorite_factions_faction");

                    b.HasOne("AgeNexus.Domain.Players.PlayerProfile", null)
                        .WithMany()
                        .HasForeignKey("PlayerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_player_favorite_factions_player");
                });

            modelBuilder.Entity("AgeNexus.Domain.Players.PlayerProfile", b =>
                {
                    b.HasOne("AgeNexus.Infrastructure.Identity.ApplicationUser", null)
                        .WithOne()
                        .HasForeignKey("AgeNexus.Domain.Players.PlayerProfile", "ApplicationUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_player_profiles_application_user");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("AgeNexus.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("AgeNexus.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgeNexus.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("AgeNexus.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AgeNexus.Domain.Competition.TeamLineup", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("AgeNexus.Domain.Matches.Match", b =>
                {
                    b.Navigation("Teams");
                });

            modelBuilder.Entity("AgeNexus.Domain.Matches.MatchTeam", b =>
                {
                    b.Navigation("Participants");
                });
#pragma warning restore 612, 618
        }
    }
}
