// <auto-generated />
using System;
using AgeNexus.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AgeNexus.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AgeNexusDbContext))]
    [Migration("20260830161700_InitialFoundation")]
    partial class InitialFoundation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AgeNexus.Domain.GameCatalog.AiDifficulty", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("GameEditionId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_edition_id");

                    b.Property<int>("InternalLevel")
                        .HasColumnType("integer")
                        .HasColumnName("internal_level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_ai_difficulties");

                    b.HasIndex("GameEditionId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_ai_difficulties_edition_name");

                    b.ToTable("ai_difficulties", "public", t =>
                        {
                            t.HasCheckConstraint("ck_ai_difficulties_internal_level", "internal_level BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("AgeNexus.Domain.Matches.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CreatedByPlayerProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_player_profile_id");

                    b.Property<Guid>("GameEditionId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_edition_id");

                    b.Property<string>("Nature")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("nature");

                    b.Property<DateTimeOffset>("PlayedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("played_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_matches");

                    b.HasIndex("CreatedByPlayerProfileId")
                        .HasDatabaseName("ix_matches_created_by_player_profile");

                    b.HasIndex("PlayedAtUtc")
                        .HasDatabaseName("ix_matches_played_at_utc");

                    b.HasIndex("GameEditionId", "Status")
                        .HasDatabaseName("ix_matches_edition_status");

                    b.ToTable("matches", "public");
                });

            modelBuilder.Entity("AgeNexus.Domain.Matches.MatchParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AiDifficultyId")
                        .HasColumnType("uuid")
                        .HasColumnName("ai_difficulty_id");

                    b.Property<Guid?>("FactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("faction_id");

                    b.Property<string>("FactionSelection")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("faction_selection");

                    b.Property<Guid?>("PlayerProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_profile_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.Property<Guid>("team_id")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.HasKey("Id")
                        .HasName("pk_match_participants");

                    b.HasIndex("AiDifficultyId")
                        .HasDatabaseName("ix_match_participants_ai_difficulty");

                    b.HasIndex("FactionId")
                        .HasDatabaseName("ix_match_participants_faction");

                    b.HasIndex("PlayerProfileId")
                        .HasDatabaseName("ix_match_participants_player_profile");

                    b.HasIndex("team_id")
                        .HasDatabaseName("ix_match_participants_team");

                    b.ToTable("match_participants", "public", t =>
                        {
                            t.HasCheckConstraint("ck_match_participants_identity", "(type = 'Human' AND player_profile_id IS NOT NULL AND ai_difficulty_id IS NULL) OR (type = 'ArtificialIntelligence' AND player_profile_id IS NULL AND ai_difficulty_id IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("AgeNexus.Domain.Matches.MatchTeam", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("result");

                    b.Property<Guid>("match_id")
                        .HasColumnType("uuid")
                        .HasColumnName("match_id");

                    b.HasKey("Id")
                        .HasName("pk_match_teams");

                    b.HasIndex("match_id", "Position")
                        .IsUnique()
                        .HasDatabaseName("ux_match_teams_match_position");

                    b.ToTable("match_teams", "public");
                });

            modelBuilder.Entity("AgeNexus.Domain.Players.PlayerProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ApplicationUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_user_id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.HasKey("Id")
                        .HasName("pk_player_profiles");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique()
                        .HasDatabaseName("ux_player_profiles_application_user_id")
                        .HasFilter("application_user_id IS NOT NULL");

                    b.HasIndex("DisplayName")
                        .HasDatabaseName("ix_player_profiles_display_name");

                    b.ToTable("player_profiles", "public");
                });

            modelBuilder.Entity("AgeNexus.Domain.Matches.Match", b =>
                {
                    b.HasOne("AgeNexus.Domain.Players.PlayerProfile", null)
                        .WithMany()
                        .HasForeignKey("CreatedByPlayerProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_matches_created_by_player_profile");
                });

            modelBuilder.Entity("AgeNexus.Domain.Matches.MatchParticipant", b =>
                {
                    b.HasOne("AgeNexus.Domain.GameCatalog.AiDifficulty", null)
                        .WithMany()
                        .HasForeignKey("AiDifficultyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_match_participants_ai_difficulty");

                    b.HasOne("AgeNexus.Domain.Players.PlayerProfile", null)
                        .WithMany()
                        .HasForeignKey("PlayerProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_match_participants_player_profile");

                    b.HasOne("AgeNexus.Domain.Matches.MatchTeam", null)
                        .WithMany("Participants")
                        .HasForeignKey("team_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_match_participants_team");
                });

            modelBuilder.Entity("AgeNexus.Domain.Matches.MatchTeam", b =>
                {
                    b.HasOne("AgeNexus.Domain.Matches.Match", null)
                        .WithMany("Teams")
                        .HasForeignKey("match_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_match_teams_match");
                });

            modelBuilder.Entity("AgeNexus.Domain.Matches.Match", b =>
                {
                    b.Navigation("Teams");
                });

            modelBuilder.Entity("AgeNexus.Domain.Matches.MatchTeam", b =>
                {
                    b.Navigation("Participants");
                });
#pragma warning restore 612, 618
        }
    }
}

