namespace AgeNexus.Infrastructure.GameCatalog;

internal static class Age2DefinitiveEditionCatalog
{
    public const string SourceVersion = "101.103.48987.0";

    public static readonly IReadOnlyCollection<CatalogItem> Civilizations =
    [
        new("achaemenids", "Aquemênidas"),
        new("armenians", "Armênios"),
        new("aztecs", "Astecas"),
        new("athenians", "Atenienses"),
        new("bengalis", "Bengalis"),
        new("berbers", "Berberes"),
        new("burmese", "Birmaneses"),
        new("byzantines", "Bizantinos"),
        new("bohemians", "Boêmios"),
        new("burgundians", "Borgonheses"),
        new("britons", "Bretões"),
        new("bulgarians", "Búlgaros"),
        new("celts", "Celtas"),
        new("muisca", "Chibchas"),
        new("chinese", "Chineses"),
        new("koreans", "Coreanos"),
        new("cumans", "Cumanos"),
        new("dravidians", "Dravidianos"),
        new("slavs", "Eslavos"),
        new("spanish", "Espanhóis"),
        new("spartans", "Espartanos"),
        new("ethiopians", "Etíopes"),
        new("franks", "Francos"),
        new("georgians", "Georgianos"),
        new("goths", "Godos"),
        new("indians", "Hindustânis"),
        new("huns", "Hunos"),
        new("incas", "Incas"),
        new("italians", "Italianos"),
        new("japanese", "Japoneses"),
        new("jurchens", "Jurchéns"),
        new("khmer", "Khmers"),
        new("lithuanians", "Lituanos"),
        new("macedonians", "Macedônios"),
        new("magyars", "Magiares"),
        new("mayans", "Maias"),
        new("malay", "Malaios"),
        new("malians", "Malineses"),
        new("mapuche", "Mapuches"),
        new("mongols", "Mongóis"),
        new("gurjaras", "Os gurjares"),
        new("persians", "Persas"),
        new("poles", "Poloneses"),
        new("portuguese", "Portugueses"),
        new("puru", "Puru"),
        new("khitans", "Quitais"),
        new("romans", "Romanos"),
        new("saracens", "Sarracenos"),
        new("shu", "Shu"),
        new("sicilians", "Sicilianos"),
        new("tatars", "Tártaros"),
        new("teutons", "Teutões"),
        new("thracians", "Trácios"),
        new("tupi", "Tupi"),
        new("turks", "Turcos"),
        new("vietnamese", "Vietnamitas"),
        new("vikings", "Vikings"),
        new("wei", "Wei"),
        new("wu", "Wu"),
    ];

    public static readonly IReadOnlyCollection<CatalogItem> Maps =
    [
        new("aoe2-map-185", "A Passagem"),
        new("aoe2-map-145", "A queda de Roma"),
        new("aoe2-map-67", "Acrópole"),
        new("aoe2-map-93", "África Ocidental"),
        new("aoe2-map-88", "Amazônia"),
        new("aoe2-map-54", "América Central"),
        new("aoe2-map-104", "Anel d'Água"),
        new("aoe2-map-132", "Antártida"),
        new("aoe2-map-202", "Aquarena"),
        new("aoe2-map-9", "Arábia"),
        new("aoe2-map-190", "Arábia QS"),
        new("aoe2-map-29", "Arena"),
        new("aoe2-map-195", "Arena QS"),
        new("aoe2-map-10", "Arquipélago"),
        new("aoe2-map-97", "Arquipélago Inimigo"),
        new("aoe2-map-150", "Atacama"),
        new("aoe2-map-205", "Atolado"),
        new("aoe2-map-107", "Austrália"),
        new("aoe2-map-11", "Báltico"),
        new("aoe2-map-115", "Barra"),
        new("aoe2-map-142", "Batalha no Gelo (BR)"),
        new("aoe2-map-58", "Bizâncio"),
        new("aoe2-map-94", "Boêmia"),
        new("aoe2-map-206", "Bosque das Trevas"),
        new("aoe2-map-207", "Bosque Real"),
        new("aoe2-map-186", "Bosques Ocos"),
        new("aoe2-map-123", "Brejo"),
        new("aoe2-map-50", "Bretanha"),
        new("aoe2-map-68", "Budapeste"),
        new("aoe2-map-71", "Buraco de Ouro"),
        new("aoe2-map-177", "Cadeia de Penhascos"),
        new("aoe2-map-34", "Canais"),
        new("aoe2-map-96", "Cânions"),
        new("aoe2-map-35", "Caprichoso"),
        new("aoe2-map-176", "Cardumes"),
        new("aoe2-map-187", "Carstes"),
        new("aoe2-map-135", "Cáucaso"),
        new("aoe2-map-37", "Cemitérios"),
        new("aoe2-map-69", "Cenotes"),
        new("aoe2-map-90", "Chifre da África"),
        new("aoe2-map-89", "China"),
        new("aoe2-map-70", "Cidade dos Lagos"),
        new("aoe2-map-101", "Círculo Interior"),
        new("aoe2-map-188", "Clareira"),
        new("aoe2-map-149", "Clareira Africana"),
        new("aoe2-map-189", "Clareira Fortificada"),
        new("aoe2-map-191", "Clareira Fortificada QS"),
        new("aoe2-map-192", "Clareira QS"),
        new("aoe2-map-14", "Continental"),
        new("aoe2-map-124", "Cordilheira"),
        new("aoe2-map-164", "Cordilheira"),
        new("aoe2-map-131", "Córregos Numerosos"),
        new("aoe2-map-180", "Corrente Dourada"),
        new("aoe2-map-152", "Cratera"),
        new("aoe2-map-79", "CtR Aleatório"),
        new("aoe2-map-81", "CtR Descida de Pirâmide"),
        new("aoe2-map-82", "CtR Espiral"),
        new("aoe2-map-80", "CtR Monção"),
        new("aoe2-map-85", "Delta do Nilo"),
        new("aoe2-map-183", "Deriva Arenosa"),
        new("aoe2-map-36", "Dingos"),
        new("aoe2-map-198", "Disputa de Fronteira"),
        new("aoe2-map-99", "Distante"),
        new("aoe2-map-181", "Dunas da Montanha"),
        new("aoe2-map-143", "El Dorado (BR)"),
        new("aoe2-map-200", "Encalhado"),
        new("aoe2-map-157", "Encosta"),
        new("aoe2-map-153", "Encruzilhadas"),
        new("aoe2-map-182", "Entrerrios"),
        new("aoe2-map-158", "Erupção"),
        new("aoe2-map-25", "Escandinávia"),
        new("aoe2-map-72", "Esconderijo"),
        new("aoe2-map-43", "Estações"),
        new("aoe2-map-75", "Estepe"),
        new("aoe2-map-110", "Estreito de Malaca"),
        new("aoe2-map-17", "Febre do Ouro"),
        new("aoe2-map-111", "Filipinas"),
        new("aoe2-map-148", "Floresta Costeira"),
        new("aoe2-map-130", "Floresta da Serpente"),
        new("aoe2-map-44", "Floresta de Sherwood"),
        new("aoe2-map-12", "Floresta Negra"),
        new("aoe2-map-196", "Floresta Negra QS"),
        new("aoe2-map-128", "Florestas Gêmeas"),
        new("aoe2-map-173", "Fontes Sagradas"),
        new("aoe2-map-16", "Fortaleza"),
        new("aoe2-map-166", "Fortaleza do Anel"),
        new("aoe2-map-210", "Fortaleza do Círculo de Pedra"),
        new("aoe2-map-73", "Forte de Colina"),
        new("aoe2-map-39", "Fossos"),
        new("aoe2-map-155", "Fossos de Equipe"),
        new("aoe2-map-55", "França"),
        new("aoe2-map-213", "Fronte Rochosa"),
        new("aoe2-map-119", "Fronteira de Pedra"),
        new("aoe2-map-47", "Geleiras de Equipe"),
        new("aoe2-map-209", "Glacis"),
        new("aoe2-map-197", "Grande Muralha"),
        new("aoe2-map-199", "Graupel"),
        new("aoe2-map-170", "Haboob"),
        new("aoe2-map-78", "Hamburger"),
        new("aoe2-map-49", "Ibéria"),
        new("aoe2-map-40", "Ilha Paradisíaca"),
        new("aoe2-map-156", "Ilha Vulcânica"),
        new("aoe2-map-19", "Ilhas"),
        new("aoe2-map-23", "Ilhas de Equipe"),
        new("aoe2-map-112", "Ilhas de Pântano"),
        new("aoe2-map-117", "Ilhas de Selva"),
        new("aoe2-map-165", "Ilhas do Norte"),
        new("aoe2-map-114", "Ilhas do Pacífico"),
        new("aoe2-map-98", "Ilhas Inimigas"),
        new("aoe2-map-146", "Império Majapahit (BR)"),
        new("aoe2-map-91", "Índia"),
        new("aoe2-map-108", "Indochina"),
        new("aoe2-map-109", "Indonésia"),
        new("aoe2-map-203", "Invasão da Floresta"),
        new("aoe2-map-178", "Istmo"),
        new("aoe2-map-53", "Itália"),
        new("aoe2-map-27", "Iucatã"),
        new("aoe2-map-129", "Jornada ao Sul"),
        new("aoe2-map-171", "Kawasan"),
        new("aoe2-map-15", "Lago da Cratera"),
        new("aoe2-map-32", "Lago Fantasma"),
        new("aoe2-map-159", "Lago Gélido"),
        new("aoe2-map-211", "Lago Ness"),
        new("aoe2-map-122", "Lagos Alpinos"),
        new("aoe2-map-126", "Langshan"),
        new("aoe2-map-100", "Linha de Frente"),
        new("aoe2-map-118", "Linha Sagrada"),
        new("aoe2-map-13", "Litorâneo"),
        new("aoe2-map-74", "Lombardia"),
        new("aoe2-map-92", "Madagáscar"),
        new("aoe2-map-113", "Manguezal"),
        new("aoe2-map-133", "Mar de Aral"),
        new("aoe2-map-57", "Mar do Japão (Mar do Leste)"),
        new("aoe2-map-134", "Mar Negro"),
        new("aoe2-map-184", "Matagal"),
        new("aoe2-map-20", "Mediterrâneo"),
        new("aoe2-map-77", "Mega-Aleatório"),
        new("aoe2-map-162", "Mercado"),
        new("aoe2-map-38", "Metrópole"),
        new("aoe2-map-154", "Michi"),
        new("aoe2-map-21", "Migração"),
        new("aoe2-map-26", "Mongólia"),
        new("aoe2-map-212", "Muralha"),
        new("aoe2-map-179", "Nascentes da Duna"),
        new("aoe2-map-46", "Naufrágio"),
        new("aoe2-map-105", "Ninho de Cobras"),
        new("aoe2-map-33", "Nômade"),
        new("aoe2-map-116", "Nômade de Água"),
        new("aoe2-map-141", "Nômade de Terra"),
        new("aoe2-map-193", "Nômade QS"),
        new("aoe2-map-106", "O Olho"),
        new("aoe2-map-31", "Oásis"),
        new("aoe2-map-151", "Ocupar a Montanha"),
        new("aoe2-map-51", "Oriente Médio"),
        new("aoe2-map-175", "Pântano"),
        new("aoe2-map-139", "Pântano Dourado"),
        new("aoe2-map-28", "Pântano Salgado"),
        new("aoe2-map-147", "Passagem da Amazônia"),
        new("aoe2-map-84", "Passo de Montanha"),
        new("aoe2-map-167", "Pedras Rúnicas"),
        new("aoe2-map-194", "Pedras Rúnicas QS"),
        new("aoe2-map-208", "Pedreira de Dorothea"),
        new("aoe2-map-41", "Peregrinos"),
        new("aoe2-map-103", "Planícies Abertas"),
        new("aoe2-map-204", "Poço do Caos"),
        new("aoe2-map-42", "Pradaria"),
        new("aoe2-map-163", "Prado"),
        new("aoe2-map-140", "Quatro Lagos"),
        new("aoe2-map-144", "Queda de Axum (BR)"),
        new("aoe2-map-83", "Quilimanjaro"),
        new("aoe2-map-125", "Ravinas"),
        new("aoe2-map-169", "Reclusão"),
        new("aoe2-map-168", "Resquícios"),
        new("aoe2-map-127", "Rio Sinuoso"),
        new("aoe2-map-22", "Rios"),
        new("aoe2-map-201", "Sardes"),
        new("aoe2-map-86", "Serengeti"),
        new("aoe2-map-136", "Sibéria"),
        new("aoe2-map-87", "Socotra"),
        new("aoe2-map-214", "Tâmisa"),
        new("aoe2-map-95", "Terra"),
        new("aoe2-map-172", "Terra Insana"),
        new("aoe2-map-102", "Terra-mãe"),
        new("aoe2-map-18", "Terras Altas"),
        new("aoe2-map-161", "Terras Baixas"),
        new("aoe2-map-56", "Terras Nórdicas"),
        new("aoe2-map-174", "Terreno Tortuoso"),
        new("aoe2-map-160", "Terreno Verde"),
        new("aoe2-map-52", "Texas"),
        new("aoe2-map-121", "Travessias Silvestres"),
        new("aoe2-map-76", "Vale"),
        new("aoe2-map-215", "Vulpinos"),
        new("aoe2-map-120", "Yin-Yang"),
    ];

    internal sealed record CatalogItem(string Slug, string Name);
}

